.Dd March 14, 2022
.Dt SHTPL 1
.Os
.Sh NAME
.Nm shtpl
.Nd shell template program
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
copies standard input to its standard output, substituting shell commands
enclosed within '{{}}' blocks with their output.
.Sh OPTIONS
None
.Sh AUTHOR
.An Mario Forzanini Aq Mt mario.forzanini@studenti.unimi.it